---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_stdout_callback: yaml
  roles:
    - deploy
    - configure-prometheus-node-exporter
