---
- name: Creates directory
  file:
    path: /home/ec2-user/backend
    state: directory

- name: "move backend files to server."
  copy:
    src: /root/project/backend
    dest: /home/ec2-user

  
- name: Executing node
  become: yes
  shell: |
    cd /home/ec2-user/backend/dist
    pm2 start npm --name backend --start