---
- name: Creates directory
  file:
    path: /home/ec2-user/backend
    state: directory

- name: "move backend files to server."
  copy:
    src: /root/project/backend
    dest: /home/ec2-user/backend

# - name: "update apt packages."
#   become: yes
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

# - name: "remove dependencies that are no longer required"
#   become: yes
#   apt:
#     autoremove: yes

# - name: "install nodejs and npm"
#   become: yes
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install n"
#   become: yes
#   npm:
#     name: n
#     global: yes
#     production: yes

# - name: "install nodejs 13.8.0"
#   become: yes
#   shell: n 13.8.0

# - name: "install pm2"
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: add repo for nodesource
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
    update_cache: yes

- name: install nodejs
  apt: 
    name: nodejs
    become: yes
    state: latest
    update_cache: yes

- name: install NPM
    name: npm
    become: yes
    args:
      path: /home/ubuntu

- name: Install PM2
  npm:
    name: pm2
    global: yes